/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"addStore" | "calculate" | "dashboard" | "dashboardnew" | "fullscreen-exit" | "fullscreen" | "generate_table" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "keyword" | "search" | "smile" | "submitproject" | "table" | "vip">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"addStore" | "calculate" | "dashboard" | "dashboardnew" | "fullscreen-exit" | "fullscreen" | "generate_table" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "keyword" | "search" | "smile" | "submitproject" | "table" | "vip">;
          default: string;
          required: true;
      };
  }>>, {
      name: "addStore" | "calculate" | "dashboard" | "dashboardnew" | "fullscreen-exit" | "fullscreen" | "generate_table" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "keyword" | "search" | "smile" | "submitproject" | "table" | "vip";
  }>;
  export const svgNames: ["addStore", "calculate", "dashboard", "dashboardnew", "fullscreen-exit", "fullscreen", "generate_table", "keyboard-down", "keyboard-enter", "keyboard-esc", "keyboard-up", "keyword", "search", "smile", "submitproject", "table", "vip"];
  export type SvgName = "addStore" | "calculate" | "dashboard" | "dashboardnew" | "fullscreen-exit" | "fullscreen" | "generate_table" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "keyword" | "search" | "smile" | "submitproject" | "table" | "vip";
  export default SvgIcon;
}
